"""Reference-adapter web intents: the concrete Shared-File Intent vocabulary for a
web/backend adapter that governs shared export barrels, routers, and DI
containers. Organized by tier:

  Tier 1 (auto-resolved, synchronous): AddExport, AddRoute, AddProviderBinding,
    RenameExport, MoveRoute, DeprecateExport — handled by the Intent Service with
    no human gate, like any additive intent.
  Tier 2 (async human review): not expressed as intent types; the Intent Service
    returns IntentRejection.reason="pending_tier2_review" when a submitted intent
    exceeds the additive vocabulary but qualifies for async review (e.g., a batch
    of intents exceeding GovernancePolicy.max_intents_per_shared_file). The
    proposing agent parks the dependent sub-task and continues other work.
  Tier 3 (synchronous full pause): not expressed as intent types; the Intent Service
    returns reason="structural" and the SOP fires (structural_change_runbook.md).

New intent operations for the reference web adapter (or a variant of it) belong here.

This module is adapter-side. Core does not import from it -- IntentOutcome.intent
in `design.plans.contracts.orchestration` is typed as dict[str, Any] precisely so Core can
route on the `op` string field without knowing the concrete union defined below.
See core_adapter_boundary.md §3.

Parsing discipline: agent-produced. Shared-file intents are generated by Task Dev agents and MUST be routed through the normalization layer before Core applies them.
"""

from __future__ import annotations

from typing import Literal

from pydantic import Field

from design.plans.contracts import BaseContract

# ---------------------------------------------------------------------------
# Shared-File Intents  (design doc §4.2)
# ---------------------------------------------------------------------------


class AddExport(BaseContract):
    """Register a new named export from a module in a shared export barrel."""

    op: Literal["add_export"] = "add_export"
    name: str
    source_module: str


class AddRoute(BaseContract):
    """Register a new route on a shared router."""

    op: Literal["add_route"] = "add_route"
    path: str
    handler: str
    middleware: list[str] = Field(default_factory=list)


class AddProviderBinding(BaseContract):
    """Register a new binding in a shared DI container."""

    op: Literal["add_provider_binding"] = "add_provider_binding"
    interface: str
    implementation: str
    scope: Literal["singleton", "transient", "scoped"]


class RenameExport(BaseContract):
    """Tier 1: Rename an existing named export in a shared export barrel.

    Deterministic and reversible: Core finds the old name in the structural map,
    applies the rename via AST transform, and updates the map atomically. All
    consumers that referenced the old name are listed in the rejection's
    `blocking_keys` if a collision occurs -- the same collision protocol as
    additive intents."""

    op: Literal["rename_export"] = "rename_export"
    old_name: str
    new_name: str


class MoveRoute(BaseContract):
    """Tier 1: Move an existing route to a different path in a shared router.

    Deterministic: Core updates the path in the structural map and applies the
    AST transform. The old path must exist in the map; the new path must not.
    Collision key is `new_path` -- two agents cannot claim the same destination."""

    op: Literal["move_route"] = "move_route"
    old_path: str
    new_path: str


class DeprecateExport(BaseContract):
    """Tier 1: Mark an existing named export as deprecated, pointing consumers
    to an alternative. Does not remove the export -- removal is Tier 3
    (structural_change_runbook.md). Safe to apply without consumer coordination
    because the export continues to exist; consumers see the deprecation at
    their next review cycle."""

    op: Literal["deprecate_export"] = "deprecate_export"
    name: str
    reason: str
    alternative: str | None = None  # optional migration target


# Discriminated union of all Tier 1 intents (additive and structural-but-safe).
# The Intent Service routes on `op` without an isinstance() chain.
# Tier 2 and Tier 3 outcomes are not expressed as intent types -- they are
# expressed as IntentRejection.reason values returned to the submitting agent
# (see design/plans/contracts/orchestration.py IntentRejection).
SharedFileIntent = (
    AddExport | AddRoute | AddProviderBinding
    | RenameExport | MoveRoute | DeprecateExport
)

class DOMCaptureConfig(BaseContract):
    await_hydration_ms: int = Field(5000, description="Minimum time to wait for quiescence")
    ignore_selectors: list[str] = Field(default_factory=list, description="CSS selectors to exclude from baseline diff")
